---
- name: Install Xray
  hosts: xray
  become: true
  vars:
    xray_install_script_url: "https://github.com/XTLS/Xray-install/raw/main/install-release.sh"
    xray_install_script_dest: "/tmp/install-release.sh"
    xray_binary_path: "/usr/local/bin/xray"
    xray_local_config_path: "/Users/andreytsybin/Documents/Github/xray/xray/reality_config_simple.json"
    xray_remote_config_path: "/usr/local/etc/xray/config.json"

  tasks:
    - name: Check if Xray is already installed
      ansible.builtin.stat:
        path: "{{ xray_binary_path }}"
      register: xray_installed

    - name: Download the Xray install script
      ansible.builtin.get_url:
        url: "{{ xray_install_script_url }}"
        dest: "{{ xray_install_script_dest }}"
        mode: '0755'
      when: not xray_installed.stat.exists

    - name: Run the Xray install script
      ansible.builtin.command: "bash -c {{ xray_install_script_dest }} @ install"
      when: not xray_installed.stat.exists

    - name: Clean up the Xray install script
      ansible.builtin.file:
        path: "{{ xray_install_script_dest }}"
        state: absent
      when: not xray_installed.stat.exists

    - name: Copy xray config from local to remote
      ansible.builtin.copy:
        src: "{{xray_local_config_path}}"
        dest: "{{xray_remote_config_path}}"
        owner: root
        group: root
        mode: '0644'

    - name: Restart XRAY
      service:
        name: xray
        state: restarted